### ISSUE TITLE
epo:  General reference Ontology Methodology

### ISSUE THREAD

**Issue by muricna** [OP-TED/epo-docs#14]
**Suggestion re improving Documentation**
Do not publish this for the time being it is not complete and not very current we need to decide whether we put this in the business overview or whether we keep a separate section.

**Comment by NPJ-OP-LUX** [comment]
Ok, noted.

**Comment by NPJ-OP-LUX** [comment]
Removed from the nav and noted for future update.

**Comment by NPJ-OP-LUX** [comment]
A Methodology page has been added to the ePO documentation: https://docs.ted.europa.eu/docs-staging/EPO/latest/index.html
