### ISSUE TITLE
epo Business overview chapter Representation of the eProcurement mode

### ISSUE THREAD

**Issue by muricna** [OP-TED/epo-docs#15]
**Documentation Error Detected**
**Representation of the eProcurement model** is missing mention of the main machine readable formats OWL core, OWL restrictions and SHAL_shapes

The glossary is not a representation of the ontology but a "dictionary" providing the definitions of concepts

**Comment by NPJ-OP-LUX** [comment]
Both points have been resolved: The missing sections have been added (OWL core, OWL restrictions and SHAL_shapes) and the glossary definition has been corrected as requested.
