### ISSUE TITLE
Documentation errors

### ISSUE THREAD

**Issue by cristianvasquez** [OP-TED/epo-docs#16]
**Documentation Error Detected**
Please describe the error you detected in as much detail including on which page it was detected.

1. In the section '3.4. XML to RDF data transformation' I think it should say XML format instead of XML formal.

2. The link to: https://data.europa.eu/collection-id/local-register-space is not there anymore.

3. The acronym PURI is not explained. This was difficuly because I could not find what a PURI is (or stands for) after a search on Google and Wikipedia.

Looking into some of the research papers, I saw it stands for Persistent URI or Persistent Uniform Identifier (in the past, these were called PURLs). I found another reference here: 
https://joinup.ec.europa.eu/collection/semic-support-centre/news/eu-institutions-define-comm.

**Comment by NPJ-OP-LUX** [comment]
The comments have been addressed/ corrected.
