### ISSUE TITLE
The links in the navigation bar of previous version (3.1.0) point to the latest version

### ISSUE THREAD

**Issue by csnyulas** [OP-TED/epo-docs#17]
**Documentation Error Detected**

The links in the left hand side navigation bar of some of the previous EPO versions (it was observed in v. 3.1.0 but others should be also checked) are pointing to the latest version of EPO documentation, not to the version that we were looking at (e.g. 3.1.0).

![image](https://github.com/OP-TED/epo-docs/assets/2441046/8d56e15d-4749-4d67-995e-f4e920418bfa)

**Comment by NPJ-OP-LUX** [comment]
Thank-you for pointing this out. It has been corrected.
