### ISSUE TITLE
add different versions of  https://docs.ted.europa.eu/epo-home/index.html 

### ISSUE THREAD

**Issue by AchillesDougalis** [OP-TED/epo-docs#18]
**Suggestion re improving Documentation**

1) Following this [link](https://docs.ted.europa.eu/epo-home/index.html)  one can see an ePO version-agnostic home webpage with links to the lastest release. 

![image](https://github.com/OP-TED/epo-docs/assets/143995053/26ff719d-7ef9-4308-b31d-b51f3bb8508f)

2 ) On the left side panel  (see picture below), when someone presses the 4.1.0-rc1, 4.0.0 or 3.0.1 links, currently he is sent to an `index.html` page showing the release notes for that version. Wouldn't it be better  if instead of that index page, one could get to a `home/index.html`  page for that corresponding version? 

![2024-02-09_17-56](https://github.com/OP-TED/epo-docs/assets/143995053/11cf9a6e-136f-4313-b04f-07e2ac752c32)

**Comment by NPJ-OP-LUX** [comment]
Yes, this is being worked on currently. It should not be too much longer.

**Comment by NPJ-OP-LUX** [comment]
The index.adoc  pages for versions 3.1.0, 4.0.0 and 4.1.0 have been updated as requested. They will be visible after the next documentation generation cycle.
