### ISSUE TITLE
Remove attachment links from nav.adoc

### ISSUE THREAD

**Issue by rousso** [OP-TED/epo-docs#3]
In modules/ROOT/nav.adoc, there are two links to BDTI and RED2015 which use the {attachmentsDir} attribute.
As the href created is relative, these links do not work when the user navigates to module other than the ROOT module (e.g. the meetings module).
To resolve this the only thing we can do is remove these links from nav.adoc and create an asciidoc page in the ROOT module that references them.

**Comment by NPJ-OP-LUX** [comment]
Two pages were created in v2.0.1 linked to from the nav.adoc menu. This issue is resolved.
